name = "botgroup-chat"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "bgkv"
id = "bc27f42a43e64fa288aa77eff80352da"

[[d1_databases]]
binding = "bgdb"
database_name = "friends"
database_id = "8f3f7e10-1474-4daa-aa96-498352fd4505"
